name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  getwidget: ^7.0.0
  device_preview: ^1.1.0
  flutter_svg: ^2.1.6
<<<<<<< Updated upstream
  path_provider: ^2.0.15
  image_picker: ^0.8.7+6
=======
  image_picker: ^1.0.4

>>>>>>> Stashed changes

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/Web-logo.svg
    - assets/Webapp.svg
    - assets/menu-icon.svg
    - assets/home.svg
    - assets/bookmark.svg
    - assets/profile.svg
    - assets/settings.svg
    - assets/info.svg
    - assets/logout.svg
    - assets/bell.svg
    - assets/file.svg
    - assets/leaderboard.svg
    - assets/message.svg
    - assets/react.svg
    - assets/search.svg
